name: Windows 10

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: ' Nhập Token Ngrok '
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cài đặt Ngrok
        run: |
          sudo apt update -y
          sudo apt install curl wget qemu-kvm -y
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok
          ./ngrok config add-authtoken "${{ github.event.inputs.ngrok }}"
          nohup ./ngrok tcp --region ap 5900 &>/dev/null &
      - name: Cài Windows, Driver và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          sudo qemu-img create -f qcow2 /mnt/a.qcow2 60G
          wget -O win11.iso https://software.download.prss.microsoft.com/dbazure/Win10_22H2_English_x64v1.iso?t=a540741e-593d-4415-b6e2-6e9619284067&e=1702188552&h=abaa1b6ce05d602ab78b0a1c7726cd6c7bf6925e469a2312d0e56589130ca806
          wget -O driver.iso https://computernewb.com/isos/driver/virtio-win-0.1.240.iso
          sudo qemu-system-x86_64 -M q35,usb=on -device usb-tablet -cpu host,+avx -smp sockets=1,cores=2,threads=2 -m 12G -device virtio-balloon-pci -device qxl-vga,vgamem_mb=1024 -device virtio-net-pci,netdev=n0 -netdev user,id=n0 -boot c -device virtio-serial-pci -device virtio-rng-pci -enable-kvm -drive file=/mnt/a.qcow2 -drive file=win11.iso,media=cdrom -drive file=driver.iso,media=cdrom  -vnc :0 -bios /usr/share/ovmf/OVMF.fd
